### PR TITLE
[ENHANCE] Types Enhancement

### PR DESCRIPTION
**Pull request by anthlasserre**
Enhance the npm package with a type compatiblity that can be useful when using this package on a TypeScript project.
Open to update or suggestions to enhance this PR.

### CODE REVIEW

**Comment by Thanasis1101** [comment]
@anthlasserre that's great work ! Thanks for improving the package !
Since I don't have experience with typescript, I would appreciate it if you could confirm that this works fine in a typescript project and that it does not effect anything already working, so that I can accept and publish your changes. Also feel free to add a folder with an example typescript project (like the /example folder but for typescript) if you have one and you think would be useful.

**Comment by anthlasserre** [comment]
@Thanasis1101 Hey mate! We use in my company this package on two projects. This is normal. That is the least we can do to contribute and enhance together this package.

Yes I will investigate more in details if it's working fine and I will comme back to you with a typescript project example.

**Comment by anthlasserre** [comment]
@Thanasis1101 Will this example be right for you?
ts-gif-search-example

**Comment by anthlasserre** [comment]
@Thanasis1101 I've tested and it works

**Comment by Thanasis1101** [comment]
@anthlasserre Awesome work ! I saw and tested you changes and uploaded **v1.3.0** !

I also updated the main [README.md](https://github.com/Thanasis1101/react-native-gif-search/blob/master/README.md) and added a new README for each example([JS README](https://github.com/Thanasis1101/react-native-gif-search/blob/master/Examples/js-example/README.md) and [TS README](https://github.com/Thanasis1101/react-native-gif-search/blob/master/Examples/ts-example/README.md)), while giving you credit for the TypeScript support.

I am glad for the cooperation ! Let's keep up the good work !

**Pull request merged**
