### PR TITLE
[FEATURE] Possible to use other FlatList props

### PR DESCRIPTION
**Pull request by anthlasserre**
https://github.com/Thanasis1101/react-native-gif-search/issues/1

### CODE REVIEW

**Comment by Thanasis1101** [comment]
@anthlasserre Well done ! Let's test this and then I will accept the pull request.

**Comment by anthlasserre** [comment]
Perfect! @Thanasis1101 do you planned to update npm package today with this feature?

**Comment by Thanasis1101** [comment]
@anthlasserre Yes. I am working on some fixes and then I will update the npm and github package, hopefully today.

**Comment by anthlasserre** [comment]
Awesome 👌🏼

**Comment by Thanasis1101** [comment]
@anthlasserre The new version is now published ! 
I fixed some issues and made it look like grid view when `numColumns` > 1. Hope it works and is helpful for your project (if you are developing one or you are planning on developing one). I also updated the readme with information about the new features, while giving you credits for this feature.
Thanks for the cooperation !

**Comment by anthlasserre** [comment]
@Thanasis1101 I've just tested the new version and it's exactly what i needed. I thank you so much. Excited to improve again your dependency.
Thanks to you 🍻

**Pull request merged**
